import datetime
import os
import time
import litellm
import os 
import json
import sys
import tiktoken
import requests
# 加载本地的 cl100k_base.tiktoken 文件
from unitest_agent.model_register import model_info


headers = {"User-Agent": "FastChat Client"}

class LLMRequest:
    def __init__(self, model: str, api_base: str = ""):
        """
        Initializes an instance of the AICaller class.

        Parameters:
            model (str): The name of the model to be used.
            api_base (str): The base API url to use in case model is set to Ollama or Hugging Face
        """
        self.model = model
        self.api_base = api_base


    def get_model_list(
        self 
    ):
        if self.api_base:
            ret = requests.post(self.api_base + "/refresh_all_workers")
            assert ret.status_code == 200
            ret = requests.post(self.api_base + "/list_models")
            models = ret.json()["models"]
            # print("models:", models)
            # print("Models from controller:", models)
        else:
            models = []

        models = list(set(models))

        priority = {k: f"___{i:02d}" for i, k in enumerate(model_info)}
        models.sort(key=lambda x: priority.get(x, x))
        # logger.info(f"Models: {models}")
        # print(f"Models: {models}")
        return models


    def call_model(self, model_name, prompt: dict, max_tokens=4096):
        """
        Call the language model with the provided prompt and retrieve the response.

        Parameters:
            prompt (dict): The prompt to be sent to the language model.
            max_tokens (int, optional): The maximum number of tokens to generate in the response. Defaults to 4096.

        Returns:
            tuple: A tuple containing the response generated by the language model, the number of tokens used from the prompt, and the total number of tokens in the response.
        """
        print("model_name:", model_name)
        ret = requests.post(
            self.api_base  + "/get_worker_address", json={"model": model_name[0]}
        )

        print("ret:", ret.json())
        worker_addr = ret.json()["address"]
        print(f"model_name: {model_name}, worker_addr: {worker_addr}")
        # print("<<<<<< prompt output info >>>>>>:", prompt)
        
        if "system" not in prompt or "user" not in prompt:
            raise KeyError(
                "The prompt dictionary must contain 'system' and 'user' keys."
            )
        if prompt["system"] == "":
            messages = [{"role": "user", "content": prompt["user"]}]
        else:
            messages = [
                {"role": "system",  "content": prompt["system"]},
                {"role": "user",    "content": prompt["user"]},
            ]
        system_prompt = """
        你作为一名专家级软件测试员，负责对输入的代码片段进行彻底测试。
        你的目标是创建一套全面的测试用例，通过这些用例执行代码，发现任何可能的漏洞或问题。

        首先，细致地分析提供的代码。弄清楚它的作用、输入、输出及任何核心逻辑或运算。深入思考所有可能需要测试的不同场景和边缘案例。

        然后，头脑风暴，列出一系列你认为必须的测试用例，以彻底验证代码的准确性。对于每一个测试用例，在表格中明确以下信息：
        - 测试用例编号：一个唯一的标识符
        - 测试用例说明：对测试用例功能的说明
        - 测试用例描述：对测试目的的清晰描述
        - 目的：测试用例的目标
        - 全局变量：代码中的全局变量
        - 桩函数： 是一种在单元测试中使用的模拟函数，它用来代替被测试模块依赖的外部组件或服务
        - 输入：测试用例的输入
        - 预期输出：对于给定的输入，代码应产出的结果
        - 测试类型：测试的分类（比如，正向测试、反向测试、边界案例等）

        在以表格形式详细列出所有测试用例之后，针对每个案例编写具体的测试代码。确保测试代码遵循以下流程：

            1. 准备：设置必要的前置条件和输入
            2. 执行：运行待测代码
            3. 验证：确保实际输出与期望输出一致 add_text_iunitest

            对于每项测试，都应清晰注释说明测试的内容及其重要性。

        完成所有单独测试用例的编写后，进行复查，确保它们全面覆盖了所有场景。思考是否还需要添加额外的测试以确保全面性。
        最后计算并输出测试用例的语句覆盖率、分支覆盖率、路径覆盖率，并给出覆盖率报告。 代码如下：
        def binary_search(arr, target):
            left, right = 0, len(arr) - 1
        
            while left <= right:
            mid = left + (right - left) // 2  # 防止溢出
         if arr[mid] == target:
            return mid  # 找到目标，返回索引
        elif arr[mid] < target:
            left = mid + 1  # 在右半边查找
        else:
            right = mid - 1  # 在左半边查找
    
        return -1  # 未找到目标，返回-1
        """
        
        # Default Completion parameters
        # completion_params = {
        #     "model": self.model,
        #     "messages": messages,
        #     "max_tokens": max_tokens,
        #     "stream": True,
        #     "temperature": 0.2,
        #     # "encoding":enc
        # }
        if "t5" in model_name:
            repetition_penalty = 1.2
        else:
            repetition_penalty = 1.0

        # Make requests
        # gen_params = {
        #     "model": model_name[0],
        #     "prompt":  prompt["user"],
        #     #  prompt["user"],
        #     # "prompt": prompt["user"],
        #     "temperature": 0.8,
        #     "repetition_penalty": repetition_penalty,
        #     "top_p": 1.0,
        #     "max_new_tokens": max_tokens,
        #     "stop": None,
        #     "stop_token_ids": None,
        #     "echo": False,
        # }
        # gen_params = {
        #         "model": model_name[0],
        #         # "messages": messages,
        #         "prompt":  prompt["user"],
        #         "max_tokens": max_tokens,
        #         "stream": True,
        #         "temperature": 0.2,
        #         # "encoding":enc
        #     }
        gen_params = {
            "model":          'CodeShell-7B-1112',
            "prompt":         prompt["user"],
            # "message":       str(messages),
            "max_tokens":     max_tokens,
            # "stream":         False,
            "stream":         True,
            "temperature":    0.2,
            # "repetition_penalty": repetition_penalty,
            "stop": None,
            "stop_token_ids": None,
            "echo": False,
        }

    #    completion_params = {
    #         "model": self.model,
    #         "messages": messages,
    #         "max_tokens": max_tokens,
    #         "stream": True,
    #         "temperature": 0.2,
    #         # "encoding":enc
    #     }
        print("gen_params:", gen_params)
        
        response = requests.post(
            worker_addr + "/worker_generate_stream",
            headers=headers,
            json=gen_params,
            # stream=False,
            stream=False,
            timeout=100,
        )
        # data_file = resource_path('model_prices_and_context_window_backup.json')
        # # 加载本地的 model_prices_and_context_window_backup.json 文件
        # with open(data_file, 'r', encoding='utf-8') as f:
        #     custom_model_prices = json.load(f)
        # litellm.model_prices = custom_model_prices

        # file_encoding_path =  resource_path(local_encoding_path) #os.path.join(os.path.dirname(__file__), local_encoding_path)
        # # print(file_encoding_path)
        # os.environ["TIKTOKEN_CACHE_DIR"] = file_encoding_path
        
        # print("file_encoding_path:",file_encoding_path+"/cl100k_base.tiktoken")
        # encoding = tiktoken.get_encoding(   file_encoding_path+"/cl100k_base.tiktoken")
        # print("output encoding:",encoding)
            # "cl100k_base")

        # API base exception for OpenAI Compatible, Ollama and Hugging Face models
        # if (
        #     "ollama" in self.model
        #     or "huggingface" in self.model
        #     or self.model.startswith("openai/")
        # ):
        #     completion_params["api_base"] = self.api_base

        # response = litellm.completion(**completion_params)

        chunks = []
        print("Streaming results from LLM model...")
        try:
            for chunk in response.iter_lines(decode_unicode=False, delimiter=b"\0"):
                if chunk:
                    model_response = json.loads(chunk.decode())
                    print(model_response['text'], end="", flush=True)
                    time.sleep(
                    0.01
                    )
                    # print(model_response['text']['content'] or "", end="", flush=True)
                    # yield model_response
        except Exception as e:
            print(f"Error during streaming: {e}")
        print("\n")
        # # model_response = litellm.stream_chunk_builder(chunks, messages=messages)
        # for chunk in response.iter_lines(decode_unicode=False, delimiter=b"\0"):
        #     if chunk:
        #         data = json.loads(chunk.decode())
        #         yield data

        # if "WANDB_API_KEY" in os.environ:
        #     root_span = Trace(
        #         name="inference_"
        #         + datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S"),
        #         kind="llm",  # kind can be "llm", "chain", "agent" or "tool
        #         inputs={
        #             "user_prompt": prompt["user"],
        #             "system_prompt": prompt["system"],
        #         },
        #         outputs={
        #             "model_response": model_response["choices"][0]["message"]["content"]
        #         },
        #     )
        #     root_span.log(name="inference")
        # Returns: Response, Prompt token count, and Response token count
        return (
            model_response['text'],
            int(model_response["usage"]["prompt_tokens"]),
            int(model_response["usage"]["completion_tokens"]),
        )