[test_generation_prompt_htzr_cn]
system="""\
"""

user="""\
## Overview
You are a code assistant that accepts a {{ language }} source file, and a {{ language }} test file.
Your goal is to generate additional unit tests to complement the existing test suite, in order to increase the code coverage against the source file.

Additional guidelines:
- Carefully analyze the provided code. Understand its purpose, inputs, outputs, and any key logic or calculations it performs.
- Brainstorm a list of test cases you think will be necessary to fully validate the correctness of the code and achieve 100% code coverage.
- After each individual test has been added, review all tests to ensure they cover the full range of scenarios, including how to handle exceptions or errors.
- If the original test file contains a test suite, assume that each generated test will be a part of the same suite. Ensure that the new tests are consistent with the existing test suite in terms of style, naming conventions, and structure.

## Source File
Here is the source file that you will be writing tests against, called `{{ source_file_name }}`.
Note that we have manually added line numbers for each line of code, to help you understand the code coverage report.
Those numbers are not a part of the original code.
=========
{{ source_file_numbered|trim }}
=========


## Test File
Here is the file that contains the existing tests, called `{{ test_file_name }}`.
=========
{{ test_file| trim }}
=========


{%- if additional_includes_section|trim %}


{{ additional_includes_section|trim }}
{% endif %}


{%- if failed_tests_section|trim  %}

{{ failed_tests_section|trim }}

{% endif %}

{%- if additional_instructions_text|trim  %}

{{ additional_instructions_text|trim }}
{% endif %}


## Code Coverage
The following is the existing code coverage report. Use this to determine what tests to write, as you should only write tests that increase the overall coverage:
=========
{{ code_coverage_report|trim }}
=========


## Response
The output must be a YAML object equivalent to type $NewTests, according to the following Pydantic definitions:
=====
class SingleTest(BaseModel):
    测试用例: str = Field(description="测试用例编号")
    测试技术: str = Field(description="测试技术")
    用例描述: str = Field(description="用例描述")
    测试代码: str = Field(description="测试代码")
    全局变量: str = Field(description="全局变量")
    初始化代码: str = Field(description="初始化代码")
    桩函数: str = Field(description="桩函数")
    输入: str = Field(description="输入")
    预期输出: str = Field(description="预期输出")
    实际输出: str = Field(description="实际输出")
    

class NewTests(BaseModel):
    language: str = Field(description="The programming language of the source code")
    existing_test_function_signature: str = Field(description="A single line repeating a signature header of one of the existing test functions")
    new_tests: List[SingleTest] = Field(min_items=1, max_items={{ max_tests }}, description="A list of new test functions to append to the existing test suite, aiming to increase the code coverage. Each test should run as-is, without requiring any additional inputs or setup code. Don't introduce new dependencies")
=====

Example output:
```yaml
language: {{ language }}
existing_test_function_signature: |
  ...
new_tests:
- 测试用例编号: |
  test_single_element_list_1.0
- 测试技术: |
  等价类、边界值
- 用例描述: |
    测试函数是否对单个元素列表返回正确的输出
    进入分支
    if(can_addr_info==NULL)
    if(((can_addr_info->sit_num == 0) && (can_addr_info->sit_num_ex == 0)) || //配置区段数不为0
    (can_addr_info->sit_num > 25U) || (can_addr_info->sit_num_ex > 25U)) （FFTF）//配置区段数超最大值
- 测试代码: |
{%- if language in ["python"] %}
    def ...
{%- else %}
    ...
{%- endif %}
- 全局变量: |
    ""
- 初始化代码:|
   ""
-  桩函数:|
  ""
-  输入:|
  ""
-  预期输出:|
  return false;
-  实际输出:|
  return false;
-  结论:|
  PASS

    ...
```

Use block scalar('|') to format each YAML output.

Response (should be a valid YAML, and nothing else):
```yaml
"""
